source "http://rubygems.org"

gem 'gemmyrb'
gem 'sinatra'
gem 'faye-websocket'
gem 'slim'
gem "thin"
gem 'rerun'
gem "sass"
gem 'coffee-script'
gem 'sinatra_auth_github'
gem 'dotenv'
gem 'sinatra-cross_origin'
gem "rack-proxy"
